# Generated by Django 3.2 on 2022-02-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blog',
        ),
    ]
