# Generated by Django 3.2 on 2022-02-03 08:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
