# Generated by Django 3.2 on 2022-02-09 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20220207_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_image_url', models.URLField(blank=True, default='default.jpg', null=True)),
                ('moderators', models.ManyToManyField(related_name='subreddits_moderated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubRedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreddits_set', to='blog.blog')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_set', to='blog.subreddit')),
            ],
            options={
                'unique_together': {('subreddit', 'post')},
            },
        ),
        migrations.AddField(
            model_name='subreddit',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='subreddits', through='blog.SubRedditPost', to='blog.Blog'),
        ),
    ]
