# Generated by Django 3.2 on 2022-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_cover_image_url_subreddit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blogpost_connected',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
