# Generated by Django 3.2 on 2022-06-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220622_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
