# Generated by Django 3.2 on 2022-06-22 07:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
