# Generated by Django 3.2 on 2022-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220131_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.CharField(default='100', max_length=280),
        ),
    ]
