# Generated by Django 3.2 on 2022-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.CharField(blank=True, default='Text', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Interesting Title', max_length=150),
        ),
    ]
