# Generated by Django 3.2 on 2022-02-04 12:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220204_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
