# Generated by Django 3.2 on 2022-02-07 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='downvote',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='blog',
            name='upvote',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='blog',
            name='vote',
            field=models.ManyToManyField(blank=True, default=None, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
