# Generated by Django 3.2 on 2022-02-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='vote',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
