# Generated by Django 3.2 on 2022-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220209_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='cover_image_url',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
