# Generated by Django 3.2 on 2022-02-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_blog_blogcomment_blogpost_connected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blogpost_connected',
            new_name='blog',
        ),
    ]
